use_frameworks!

target 'FlatField_Example' do
  pod 'FlatField', :path => '../'

  target 'FlatField_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
